services:
  app:
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://shakurahmad:postgres@db:5432/finsight

  db:
    restart: unless-stopped
    image: pgvector/pgvector:pg15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=shakurahmad
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finsight
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: