"""add sentiment columns to news_articles

Revision ID: 1438674446f0
Revises: 6c52958aa401
Create Date: 2026-04-16 00:11:23.664801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1438674446f0'
down_revision: Union[str, Sequence[str], None] = '6c52958aa401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('sentiment_label', sa.String(), nullable=True))
    op.add_column('news_articles', sa.Column('sentimen_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'sentimen_confidence')
    op.drop_column('news_articles', 'sentiment_label')
    # ### end Alembic commands ###
