"""add dk_knowledge, macro_indicators, sector_macro_mapping tables

Revision ID: 5a8065585d17
Revises: 1c6cae7f0173
Create Date: 2026-04-11 15:31:52.200437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8065585d17'
down_revision: Union[str, Sequence[str], None] = '1c6cae7f0173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dk_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('sector_avg', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('upper_threshold', sa.Float(), nullable=False),
    sa.Column('lower_threshold', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_macro_map',
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sector', 'indicator_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_macro_map')
    op.drop_table('macro_indicator')
    op.drop_table('dk_knowledge')
    # ### end Alembic commands ###
