"""add watch_list and sentiment_history tables

Revision ID: aea200c1b44f
Revises: 5a8065585d17
Create Date: 2026-04-12 13:21:37.312278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea200c1b44f'
down_revision: Union[str, Sequence[str], None] = '5a8065585d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_history',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('watch_list',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_list')
    op.drop_table('sentiment_history')
    # ### end Alembic commands ###
