"""add anomaly_features table

Revision ID: e404aaea36e6
Revises: aea200c1b44f
Create Date: 2026-04-13 14:29:57.318683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e404aaea36e6'
down_revision: Union[str, Sequence[str], None] = 'aea200c1b44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_features',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('earnings_surprise', sa.Float(), nullable=False),
    sa.Column('insider_volume', sa.Float(), nullable=False),
    sa.Column('filing_frequency', sa.Float(), nullable=False),
    sa.Column('price_volatility', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_features')
    # ### end Alembic commands ###
