"""fix: type in sentiment_confidence

Revision ID: f2d763462c00
Revises: 1438674446f0
Create Date: 2026-04-16 00:12:21.324720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d763462c00'
down_revision: Union[str, Sequence[str], None] = '1438674446f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('sentiment_confidence', sa.Float(), nullable=True))
    op.drop_column('news_articles', 'sentimen_confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('sentimen_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('news_articles', 'sentiment_confidence')
    # ### end Alembic commands ###
