name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: postgresql://shakurahmad:postgres@localhost:5432/finsight
      NEWS_API: ${{ secrets.NEWS_API }}
    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_USER: shakurahmad
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: finsight
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt
      - run: |
          until pg_isready -h localhost -p 5432; do 
            echo "Waiting for database..."
            sleep 1
          done
      - run: alembic upgrade head
      - run: pytest tests

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/finsight
            git pull origin main 
            docker-compose down && docker-compose up -d --build
    

